spring:
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://db:5432/homework_user
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      example:
        springhomework: DEBUG

feign:
  circuitbreaker:
    enabled: true