services:
  app:
    image: 'spring-homework:latest'
    build: 
      context: .
    container_name: app
    depends_on:
      - db
    profiles:
      - main
  
  db:
    image: 'postgres:14.7-alpine3.17'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - homework-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  homework-postgres-data: