services:
  proxy:
    image: 'nginx:stable-alpine-perl'
    networks:
      - nginx_network
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"

  app:
    image: 'spring-homework:latest'
    build: 
      context: .
    networks:
      - nginx_network
      - backend
    container_name: app
    depends_on:
      - db
    profiles:
      - main
  
  db:
    image: 'postgres:14.7-alpine3.17'
    networks:
      - backend
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - homework-postgres-data:/var/lib/postgresql/data

volumes:
  homework-postgres-data:

networks:
  backend:
    driver: bridge
  nginx_network:
    driver: bridge